version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV:-production} # Set to 'production' if this is for production
      DATABASE_HOST: ${DATABASE_HOST:-localhost} # External MySQL host (localhost if on the same EC2 instance)
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root} # MySQL username
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password} # MySQL password
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dog_app_backend_production} # Your production database name
